name: example
on:
  issues:
  workflow_dispatch:
    inputs:
      hackme:
        type: string
        default: "unsafe"

jobs:
  vulnerable-1:
    runs-on: ubuntu-latest
  
    steps:
      - name: vulnerable-inputs
        run: |
          echo "doing a thing: ${{ inputs.hackme }}"
